In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [50]:
train = pd.read_csv("train.csv")
train.head()
test = pd.read_csv("test.csv")

In [51]:
### Find the count of missing values in train dataset(train.csv)
train.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [89]:
#### Combine both the test and train datasets
df = train.append(test)

In [90]:
df.head()

,ApplicantIncome,CoapplicantIncome,Credit_History,Dependents,Education,Gender,LoanAmount,Loan_Amount_Term,Loan_ID,Loan_Status,Married,Property_Area,Self_Employed
0,5849,0.0,1.0,0,Graduate,Male,NaN,360.0,LP001002,Y,No,Urban,No
1,4583,1508.0,1.0,1,Graduate,Male,128.0,360.0,LP001003,N,Yes,Rural,No
2,3000,0.0,1.0,0,Graduate,Male,66.0,360.0,LP001005,Y,Yes,Urban,Yes
3,2583,2358.0,1.0,0,Not Graduate,Male,120.0,360.0,LP001006,Y,Yes,Urban,No
4,6000,0.0,1.0,0,Graduate,Male,141.0,360.0,LP001008,Y,No,Urban,No

In [106]:
#### Convert Gender,Married,Dependents,Education,Self_Employed,Property_Area into numeric form depending on column
df2 = pd.get_dummies(train[["Education","Gender","Dependents","Self_Employed","Married","Property_Area"]])
df2.head(5)

,Education_Graduate,Education_Not Graduate,Gender_Female,Gender_Male,Dependents_0,Dependents_1,Dependents_2,Dependents_3+,Self_Employed_No,Self_Employed_Yes,Married_No,Married_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,1,0,0,1,1,0,0,0,1,0,1,0,0,0,1
1,1,0,0,1,0,1,0,0,1,0,0,1,1,0,0
2,1,0,0,1,1,0,0,0,0,1,0,1,0,0,1
3,0,1,0,1,1,0,0,0,1,0,0,1,0,0,1
4,1,0,0,1,1,0,0,0,1,0,1,0,0,0,1

In [109]:
#df = df.drop(["Education","Gender","Dependents","Self_Employed","Married","Property_Area"],axis = 1)
df2 = df2.drop(["Education_Not Graduate","Gender_Female","Self_Employed_No","Married_No"],axis = 1)

In [110]:
df = pd.concat([df,df2],axis = 0)
df2

C:\Users\Niharikaa\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

,Education_Graduate,Gender_Male,Dependents_0,Dependents_1,Dependents_2,Dependents_3+,Self_Employed_Yes,Married_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,1,1,1,0,0,0,0,0,0,0,1
1,1,1,0,1,0,0,0,1,1,0,0
2,1,1,1,0,0,0,1,1,0,0,1
3,0,1,1,0,0,0,0,1,0,0,1
4,1,1,1,0,0,0,0,0,0,0,1
5,1,1,0,0,1,0,1,1,0,0,1
6,0,1,1,0,0,0,0,1,0,0,1
7,1,1,0,0,0,1,0,1,0,1,0
8,1,1,0,0,1,0,0,1,0,0,1
9,1,1,0,1,0,0,0,1,0,1,0
10,1,1,0,0,1,0,0,1,0,0,1
11,1,1,0,0,1,0,0,1,0,0,1
12,1,1,0,0,1,0,0,1,0,0,1
13,1,1,1,0,0,0,0,0,1,0,0
14,1,1,0,0,1,0,0,1,0,0,1
15,1,1,1,0,0,0,0,0,0,0,1
16,0,1,0,1,0,0,0,0,0,0,1
17,1,0,1,0,0,0,0,0,0,0,1
18,0,1,1,0,0,0,0,1,1,0,0
19,1,1,1,0,0,0,0,1,0,0,1
20,0,1,1,0,0,0,0,1,0,0,1
21,1,1,0,1,0,0,0,1,0,0,1
22,0,1,1,0,0,0,0,1,0,1,0
23,0,0,0,0,1,0,0,1,1,0,0
24,1,1,0,1,0,0,0,1,0,1,0
25,1,1,1,0,0,0,1,1,0,1,0
26,1,1,1,0,0,0,0,1,0,1,0
27,0,1,0,0,1,0,0,1,0,0,1
28,0,1,1,0,0,0,0,0,0,0,1
29,1,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
584,1,1,0,1,0,0,0,1,1,0,0
585,1,1,0,1,0,0,0,1,1,0,0
586,1,1,1,0,0,0,0,1,0,0,1
587,0,0,1,0,0,0,0,0,0,1,0
588,1,0,1,0,0,0,0,0,0,1,0
589,1,1,0,0,1,0,1,1,0,1,0
590,1,1,1,0,0,0,0,1,0,1,0
591,1,1,0,0,1,0,1,1,0,1,0
592,1,0,0,0,0,1,1,0,0,1,0
593,1,1,1,0,0,0,0,1,1,0,0
594,1,1,1,0,0,0,1,1,0,0,1
595,0,1,1,0,0,0,0,0,1,0,0
596,0,1,0,0,1,0,1,1,1,0,0
597,1,1,0,0,0,0,0,0,0,1,0
598,1,1,1,0,0,0,1,1,1,0,0
599,1,1,0,0,1,0,0,1,0,0,1
600,1,0,0,0,0,1,0,0,0,0,1
601,0,1,1,0,0,0,0,1,1,0,0
602,1,1,0,0,0,1,0,1,0,0,1
603,1,1,1,0,0,0,0,0,1,0,0
604,1,0,0,1,0,0,0,1,0,1,0
605,0,1,1,0,0,0,0,1,0,0,1
606,1,1,0,1,0,0,0,1,0,1,0
607,0,1,0,0,1,0,0,1,1,0,0
608,1,1,1,0,0,0,0,1,1,0,0
609,1,0,1,0,0,0,0,0,1,0,0
610,1,1,0,0,0,1,0,1,1,0,0
611,1,1,0,1,0,0,0,1,0,0,1
612,1,1,0,0,1,0,0,1,0,0,1
613,1,0,1,0,0,0,1,0,0,1,0

In [111]:
df

,ApplicantIncome,CoapplicantIncome,Credit_History,Dependents_0,Dependents_1,Dependents_2,Dependents_3+,Education_Graduate,Education_Not Graduate,Gender_Female,...,Loan_ID,Loan_Status,Married_No,Married_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Self_Employed_No,Self_Employed_Yes,"(Married, Gender, Self_Employed)"
0,5849.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001002,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,4583.0,1508.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001003,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,3000.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001005,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,2583.0,2358.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001006,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,6000.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001008,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
5,5417.0,4196.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001011,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
6,2333.0,1516.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001013,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
7,3036.0,2504.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001014,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
8,4006.0,1526.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001018,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
9,12841.0,10968.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001020,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
10,3200.0,700.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001024,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11,2500.0,1840.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001027,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
12,3073.0,8106.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001028,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
13,1853.0,2840.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001029,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
14,1299.0,1086.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001030,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
15,4950.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001032,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
16,3596.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001034,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
17,3510.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001036,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
18,4887.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001038,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
19,2600.0,3500.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001041,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
20,7660.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001043,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
21,5955.0,5625.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001046,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
22,2600.0,1911.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001047,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
23,3365.0,1917.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001050,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
24,3717.0,2925.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001052,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
25,9560.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001066,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
26,2799.0,2253.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001068,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
27,4226.0,1040.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001073,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
28,1442.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001086,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
29,3750.0,2083.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,LP001087,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,NaN,NaN,NaN,0.0,1.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,1.0,0.0,0.0,NaN,0.0,NaN
585,NaN,NaN,NaN,0.0,1.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,1.0,0.0,0.0,NaN,0.0,NaN
586,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,0.0,0.0,1.0,NaN,0.0,NaN
587,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,NaN,0.0,NaN
588,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,NaN,0.0,NaN
589,NaN,NaN,NaN,0.0,0.0,1.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,0.0,1.0,0.0,NaN,1.0,NaN
590,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,0.0,1.0,0.0,NaN,0.0,NaN
591,NaN,NaN,NaN,0.0,0.0,1.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,0.0,1.0,0.0,NaN,1.0,NaN
592,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,NaN,1.0,NaN
593,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,1.0,0.0,0.0,NaN,0.0,NaN
594,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,0.0,0.0,1.0,NaN,1.0,NaN
595,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,NaN,NaN,...,NaN,NaN,NaN,0.0,1.0,0.0,0.0,NaN,0.0,NaN
596,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,NaN,NaN,...,NaN,NaN,NaN,1.0,1.0,0.0,0.0,NaN,1.0,NaN
597,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,NaN,0.0,NaN
598,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,1.0,0.0,0.0,NaN,1.0,NaN
599,NaN,NaN,NaN,0.0,0.0,1.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,0.0,0.0,1.0,NaN,0.0,NaN
600,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,1.0,NaN,0.0,NaN
601,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,NaN,NaN,...,NaN,NaN,NaN,1.0,1.0,0.0,0.0,NaN,0.0,NaN
602,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,0.0,0.0,1.0,NaN,0.0,NaN
603,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,0.0,1.0,0.0,0.0,NaN,0.0,NaN
604,NaN,NaN,NaN,0.0,1.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,0.0,1.0,0.0,NaN,0.0,NaN
605,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,NaN,NaN,...,NaN,NaN,NaN,1.0,0.0,0.0,1.0,NaN,0.0,NaN
606,NaN,NaN,NaN,0.0,1.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,0.0,1.0,0.0,NaN,0.0,NaN
607,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,NaN,NaN,...,NaN,NaN,NaN,1.0,1.0,0.0,0.0,NaN,0.0,NaN
608,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,1.0,0.0,0.0,NaN,0.0,NaN
609,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,0.0,1.0,0.0,0.0,NaN,0.0,NaN
610,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,1.0,0.0,0.0,NaN,0.0,NaN
611,NaN,NaN,NaN,0.0,1.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,0.0,0.0,1.0,NaN,0.0,NaN
612,NaN,NaN,NaN,0.0,0.0,1.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,0.0,0.0,1.0,NaN,0.0,NaN
613,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,NaN,1.0,NaN

In [112]:
# Also show the count for each column mentioned above after converting into numeric form
df2.isna().sum()

Education_Graduate         0
Gender_Male                0
Dependents_0               0
Dependents_1               0
Dependents_2               0
Dependents_3+              0
Self_Employed_Yes          0
Married_Yes                0
Property_Area_Rural        0
Property_Area_Semiurban    0
Property_Area_Urban        0
dtype: int64

In [119]:
X_train = train.iloc[:, 1: 12].values
y_train = train.iloc[:, 12].values
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train,y_train)

C:\Users\Niharikaa\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

ValueError: could not convert string to float: 'Semiurban'